import { describe, expect, it } from "vitest";
import { coordinateAuthenticatedSessionState } from "../../modules/bank-sessions/ensure-authenticated-session";
import type { AuthenticationMutationAuthority } from "../../modules/bank-sessions/authentication-mutation-authority";
import type { SessionAuthenticationAttemptRecord, SessionAuthenticationAttemptRepository, SessionAuthenticationFailurePair } from "../../modules/bank-sessions/session-authentication-attempt-repository";
import * as subject from "./authenticated-session-mutation-runner";
import { createAuthenticatedSessionMutationRunner, isCredentialMutationFence, type AuthenticationExecutionResult, type CredentialMutationFence } from "./authenticated-session-mutation-runner";
import { executeDurablyFencedAutoLogin } from "./durable-auto-login-mutation";

const deferred = <T>() => { let resolve!: (value: T) => void; let reject!: (error: unknown) => void; const promise = new Promise<T>((done, fail) => { resolve = done; reject = fail; }); return { promise, resolve, reject }; };
type Operation = "renew" | "begin" | "barrier" | "retry" | "authenticated" | "failed";
type Mode = "ok" | "bad" | "throw";
class Scheduler {
  callback?: () => Promise<void>; starts = 0; stops = 0; startError = false; stopError = false; holdStop?: ReturnType<typeof deferred<void>>; stopped = deferred<void>();
  start(callback: () => Promise<void>) { if (this.startError) throw new Error("start"); this.callback = callback; this.starts++; return { stop: async () => { this.stops++; this.stopped.resolve(); if (this.holdStop) await this.holdStop.promise; if (this.stopError) throw new Error("stop"); } }; }
  tick() { return this.callback?.() ?? Promise.resolve(); }
}
class Fixture {
  readonly calls: string[] = []; readonly waits: Partial<Record<Operation, ReturnType<typeof deferred<void>>>> = {}; readonly started: Partial<Record<Operation, ReturnType<typeof deferred<void>>>> = {}; readonly outputs: Partial<Record<Operation, unknown>> = {}; readonly modes: Partial<Record<Operation, Mode>> = {}; inFlight = 0; maxInFlight = 0; phase = "no_credential_interaction";
  readonly identity = { bankCode: "bank", runId: "run", attemptId: "attempt" }; readonly now = new Date();
  record = (owner = true) => ({ identity: this.identity, status: "active" as const, interactionPhase: this.phase as "no_credential_interaction" | "credentials_may_have_reached_portal" | "submit_may_have_been_dispatched", failureClass: null, operatorReason: null, retryCount: 0, ownerToken: owner ? "owner" : null, generation: 0n, leaseExpiresAt: owner ? this.now : null, terminalAt: null, createdAt: this.now, updatedAt: this.now });
  async operation<T>(name: Operation, value: () => T): Promise<T> { this.calls.push(name); this.inFlight++; this.maxInFlight = Math.max(this.maxInFlight, this.inFlight); this.started[name]?.resolve(); try { await this.waits[name]?.promise; if (this.modes[name] === "throw") throw new Error(name); return Object.hasOwn(this.outputs, name) ? this.outputs[name] as T : value(); } finally { this.inFlight--; } }
  terminal(status: "authenticated" | "failed", failure?: { failureClass: string; operatorReason: string }) { return { ...this.record(false), status, generation: 1n, terminalAt: this.now, failureClass: status === "failed" ? failure!.failureClass : null, operatorReason: status === "failed" ? failure!.operatorReason : null } as SessionAuthenticationAttemptRecord; }
  repository(): SessionAuthenticationAttemptRepository { return {
    findExact: async () => ({ status: "missing" }), getOrCreate: async () => ({ status: "created", record: this.record(false) }), acquireLease: async () => ({ status: "lease_acquired", owner: { identity: this.identity, ownerToken: "owner", generation: 0n }, record: this.record() }), reconcileExpiredLease: async () => ({ status: "missing" }),
    renewLease: async () => this.operation("renew", () => this.modes.renew === "bad" ? { status: "not_applied" } : { status: "lease_renewed", record: this.record() }),
    beginCredentialInteraction: async () => this.operation("begin", () => { if (this.modes.begin === "bad") return { status: "not_applied" }; this.phase = "credentials_may_have_reached_portal"; return { status: "interaction_started", record: this.record() }; }),
    recordSubmitBarrier: async () => this.operation("barrier", () => { if (this.modes.barrier === "bad") return { status: "not_applied" }; this.phase = "submit_may_have_been_dispatched"; return { status: "recorded", record: this.record() }; }),
    claimRetry: async () => this.operation("retry", () => this.modes.retry === "bad" ? { status: "not_applied" } : { status: "retry_claimed", retryCount: 1, record: { ...this.record(false), generation: 1n, retryCount: 1 } }),
    completeAuthenticated: async () => this.operation("authenticated", () => this.modes.authenticated === "bad" ? { status: "not_applied" } : { status: "authenticated", record: this.terminal("authenticated") }),
    completeFailed: async (failure: SessionAuthenticationFailurePair) => this.operation("failed", () => this.modes.failed === "bad" ? { status: "not_applied" } : { status: "failed", record: this.terminal("failed", failure) }),
  } as unknown as SessionAuthenticationAttemptRepository; }
  async authority(): Promise<AuthenticationMutationAuthority> { const state = await coordinateAuthenticatedSessionState({ identity: this.identity, ownerToken: "owner", leaseDurationMs: 1 }, { attempts: this.repository(), probe: { observe: async () => ({ status: "unauthenticated" }) }, completion: { mode: "attempt_only" } }); if (state.status !== "authentication_required") throw new Error("mint"); return state.authority; }
}
const create = (scheduler: Scheduler, execute: (input: { fence: CredentialMutationFence; signal: AbortSignal }) => Promise<AuthenticationExecutionResult>, cancellationSignal?: AbortSignal) => createAuthenticatedSessionMutationRunner({ heartbeat: scheduler, execution: { execute }, cancellationSignal });
const phase = async (fence: { beginCredentialInteraction(): Promise<unknown>; recordSubmitBarrier(): Promise<unknown> }, value: "leased" | "interaction_started" | "submit_barrier_recorded") => { if (value !== "leased") await fence.beginCredentialInteraction(); if (value === "submit_barrier_recorded") await fence.recordSubmitBarrier(); };
const terminal = (fixture: Fixture) => fixture.calls.filter((call) => call === "retry" || call === "authenticated" || call === "failed");

describe("AuthenticatedSessionMutationRunner", () => {
  it("queues heartbeat behind deferred begin and proves one authority operation at a time", async () => { const f = new Fixture(); const s = new Scheduler(); const wait = deferred<void>(); f.waits.begin = wait; const run = create(s, async ({ fence }) => { const begin = fence.beginCredentialInteraction(); await Promise.resolve(); const tick = s.tick(); expect(f.calls).toEqual(["begin"]); expect(f.inFlight).toBe(1); wait.resolve(); await begin; await tick; return { status: "succeeded" }; }).run(await f.authority()); await expect(run).resolves.toEqual({ status: "failed", reason: "authentication_attempt_requires_review" }); expect(f.calls).toEqual(["begin", "renew", "failed"]); expect(f.maxInFlight).toBe(1); });
  it("queues heartbeat behind deferred barrier and serializes terminalization", async () => { const f = new Fixture(); const s = new Scheduler(); const wait = deferred<void>(); f.waits.barrier = wait; const run = create(s, async ({ fence }) => { await fence.beginCredentialInteraction(); const barrier = fence.recordSubmitBarrier(); await Promise.resolve(); const tick = s.tick(); expect(f.calls).toEqual(["begin", "barrier"]); wait.resolve(); await barrier; await tick; return { status: "succeeded" }; }).run(await f.authority()); await expect(run).resolves.toEqual({ status: "authenticated" }); expect(f.calls).toEqual(["begin", "barrier", "renew", "authenticated"]); expect(f.maxInFlight).toBe(1); });
  it("serializes a heartbeat and boundary renewal through the same gate without changing phase", async () => { const f = new Fixture(); const s = new Scheduler(); const wait = deferred<void>(); f.waits.renew = wait; const run = create(s, async ({ fence }) => { const boundary = fence.renewBeforeCredentialMutation(); await Promise.resolve(); const tick = s.tick(); expect([f.calls, f.inFlight, f.phase]).toEqual([["renew"], 1, "no_credential_interaction"]); wait.resolve(); await boundary; await tick; return { status: "succeeded" }; }).run(await f.authority()); await expect(run).resolves.toEqual({ status: "failed", reason: "authentication_attempt_requires_review" }); expect([f.calls, f.maxInFlight, f.phase]).toEqual([["renew", "renew", "failed"], 1, "no_credential_interaction"]); });
  it("ignores a retained callback invoked after stop", async () => { const f = new Fixture(); const s = new Scheduler(); s.holdStop = deferred<void>(); const run = create(s, async () => ({ status: "succeeded" })).run(await f.authority()); await s.stopped.promise; const late = s.tick(); await Promise.resolve(); expect(f.calls).toEqual([]); s.holdStop.resolve(); await late; await expect(run).resolves.toEqual({ status: "failed", reason: "authentication_attempt_requires_review" }); expect(f.calls).toEqual(["failed"]); });
  it("drains an in-flight heartbeat before terminalization", async () => { const f = new Fixture(); const s = new Scheduler(); const renew = deferred<void>(); const execution = deferred<AuthenticationExecutionResult>(); f.waits.renew = renew; const run = create(s, async () => execution.promise).run(await f.authority()); const tick = s.tick(); await Promise.resolve(); expect(f.inFlight).toBe(1); execution.resolve({ status: "succeeded" }); await Promise.resolve(); expect(terminal(f)).toEqual([]); renew.resolve(); await tick; await expect(run).resolves.toEqual({ status: "failed", reason: "authentication_attempt_requires_review" }); expect(terminal(f)).toEqual(["failed"]); expect(f.maxInFlight).toBe(1); });
  it("maps every result in every phase to exactly one permitted lifecycle operation", async () => { const inputs: AuthenticationExecutionResult[] = [{ status: "succeeded" }, { status: "transient_unavailable" }, { status: "cancelled" }, { status: "blocked" }, { status: "rejected", cause: "protected_or_mfa" }, { status: "rejected", cause: "incompatible_flow" }, { status: "rejected", cause: "structural_configuration" }, { status: "rejected", cause: "unknown" }]; for (const at of ["leased", "interaction_started", "submit_barrier_recorded"] as const) for (const result of inputs) { const f = new Fixture(); const outcome = await create(new Scheduler(), async ({ fence }) => { await phase(fence, at); return result; }).run(await f.authority()); const expected = result.status === "succeeded" && at === "submit_barrier_recorded" ? ["authenticated"] : (result.status === "transient_unavailable" || result.status === "cancelled") && at === "leased" ? ["retry"] : ["failed"]; expect(terminal(f)).toEqual(expected); expect(f.maxInFlight).toBe(1); if (expected[0] === "failed") { const call = f.calls.indexOf("failed"); const protectedFlow = result.status === "rejected" && result.cause === "protected_or_mfa"; const configured = result.status === "rejected" && (result.cause === "incompatible_flow" || result.cause === "structural_configuration"); expect(outcome).toEqual({ status: "failed", reason: protectedFlow ? "protected_authentication_step_detected" : configured ? "bank_login_configuration_requires_review" : "authentication_attempt_requires_review" }); expect(call).toBeGreaterThanOrEqual(0); } } });
  it("fails closed before execution when start throws and after execution when stop throws", async () => { const first = new Fixture(); const start = new Scheduler(); start.startError = true; let calls = 0; await expect(create(start, async () => { calls++; return { status: "succeeded" }; }).run(await first.authority())).resolves.toEqual({ status: "unresolved" }); expect([calls, first.calls]).toEqual([0, []]); const second = new Fixture(); const stop = new Scheduler(); stop.stopError = true; await expect(create(stop, async () => ({ status: "succeeded" })).run(await second.authority())).resolves.toEqual({ status: "unresolved" }); expect(terminal(second)).toEqual([]); });
  it("does not replay terminal or retry operations after thrown or non-applied results", async () => { for (const operation of ["retry", "failed", "authenticated"] as const) for (const mode of ["throw", "bad"] as const) { const f = new Fixture(); f.modes[operation] = mode; const result: AuthenticationExecutionResult = operation === "retry" ? { status: "transient_unavailable" } : operation === "authenticated" ? { status: "succeeded" } : { status: "blocked" }; const outcome = await create(new Scheduler(), async ({ fence }) => { if (operation === "authenticated") await phase(fence, "submit_barrier_recorded"); return result; }).run(await f.authority()); expect(outcome).toEqual({ status: "unresolved" }); expect(terminal(f)).toEqual([operation]); } });
  it("makes heartbeat failure sticky, aborts execution, and prevents terminalization", async () => { for (const mode of ["bad", "throw"] as const) { const f = new Fixture(); f.modes.renew = mode; const s = new Scheduler(); const outcome = await create(s, async ({ signal }) => { await s.tick(); expect(signal.aborted).toBe(true); return { status: "succeeded" }; }).run(await f.authority()); expect(outcome).toEqual({ status: "unresolved" }); expect(terminal(f)).toEqual([]); } });
  it("keeps an executor raw mutation blocked after boundary authorization then heartbeat abort", async () => { const f = new Fixture(); const s = new Scheduler(); let rawMutations = 0; const outcome = await create(s, async ({ fence, signal }) => { await fence.renewBeforeCredentialMutation(); f.modes.renew = "bad"; await s.tick(); const result = await executeDurablyFencedAutoLogin({ strategy: { bankCode: "bank", autoLogin: async ({ page }) => { try { await page.fill("user", "alice"); } catch {} return { status: "succeeded" }; } }, credential: { bankCode: "bank", username: "alice", password: "secret" }, page: { currentUrl: async () => "https://bank.example/login", hasVisibleSelector: async () => false, fill: async () => { rawMutations++; }, click: async () => { rawMutations++; } }, fence, signal }); return result.status === "blocked" ? { status: "blocked" } : { status: "succeeded" }; }).run(await f.authority()); expect([outcome, rawMutations, terminal(f)]).toEqual([{ status: "unresolved" }, 0, []]); });
  it("makes a caught fence block sticky so later fences cannot call authority", async () => { const f = new Fixture(); f.modes.begin = "bad"; const outcome = await create(new Scheduler(), async ({ fence, signal }) => { expect(await fence.beginCredentialInteraction()).toEqual({ status: "blocked" }); expect(await fence.recordSubmitBarrier()).toEqual({ status: "blocked" }); expect(signal.aborted).toBe(true); return { status: "succeeded" }; }).run(await f.authority()); expect(outcome).toEqual({ status: "unresolved" }); expect(f.calls).toEqual(["begin"]); expect(terminal(f)).toEqual([]); });
  it("rejects malformed execution outputs without sensitive output leaks", async () => { for (const value of [null, 1, {}, { status: "unknown" }, { status: "succeeded", password: "secret" }, { status: "rejected", cause: "unknown", token: "secret" }]) { const f = new Fixture(); const outcome = await create(new Scheduler(), async () => value as AuthenticationExecutionResult).run(await f.authority()); expect(outcome).toEqual({ status: "failed", reason: "authentication_attempt_requires_review" }); expect(JSON.stringify(outcome)).not.toMatch(/secret|token|password|error/); expect(terminal(f)).toEqual(["failed"]); } });
  it("rejects genuinely malformed fulfilled retry and terminal values without replay or leaks", async () => { for (const operation of ["retry", "authenticated", "failed"] as const) for (const value of [undefined, null, 1, {}, { status: "unknown" }, { status: "retry_claimed" }]) { const f = new Fixture(); f.outputs[operation] = value; const outcome = await create(new Scheduler(), async ({ fence }) => { if (operation === "authenticated") await phase(fence, "submit_barrier_recorded"); return operation === "retry" ? { status: "transient_unavailable" } : operation === "authenticated" ? { status: "succeeded" } : { status: "blocked" }; }).run(await f.authority()); expect(outcome, `${operation}:${JSON.stringify(value)}`).toEqual({ status: "unresolved" }); expect(terminal(f)).toEqual([operation]); expect(JSON.stringify(outcome)).not.toMatch(/raw|error|secret|token/); } });
  it("holds a terminal operation alone after stop and does not replay a deferred rejection", async () => { for (const rejected of [false, true]) { const f = new Fixture(); const s = new Scheduler(); const wait = deferred<void>(); const started = deferred<void>(); f.waits.failed = wait; f.started.failed = started; let settled = false; const run = create(s, async () => ({ status: "succeeded" })).run(await f.authority()).then((result) => { settled = true; return result; }); await started.promise; expect([f.calls, f.inFlight, s.stops, settled]).toEqual([["failed"], 1, 1, false]); await s.tick(); expect(f.calls).toEqual(["failed"]); if (rejected) wait.reject(new Error("raw")); else wait.resolve(); await expect(run).resolves.toEqual(rejected ? { status: "unresolved" } : { status: "failed", reason: "authentication_attempt_requires_review" }); expect(terminal(f)).toEqual(["failed"]); expect(f.maxInFlight).toBe(1); } });
  it("does not schedule or execute when a claimed authority is unavailable", async () => { const f = new Fixture(); const consumed = new Scheduler(); consumed.startError = true; const authority = await f.authority(); await create(consumed, async () => ({ status: "succeeded" })).run(authority); const s = new Scheduler(); let executions = 0; await expect(create(s, async () => { executions++; return { status: "succeeded" }; }).run(authority)).resolves.toEqual({ status: "unresolved" }); expect([s.starts, executions, f.calls]).toEqual([0, 0, []]); });
  it("rejects structural, copied, and proxied fence lookalikes", () => { const fake = { beginCredentialInteraction: async () => ({ status: "authorized" as const }), renewBeforeCredentialMutation: async () => ({ status: "authorized" as const }), recordSubmitBarrier: async () => ({ status: "authorized" as const }) }; expect([isCredentialMutationFence(fake), isCredentialMutationFence({ ...fake }), isCredentialMutationFence(new Proxy(fake, {}))]).toEqual([false, false, false]); });
  it("validates only the fence registered for the active execution", async () => { const f = new Fixture(); let retained: unknown; expect(isCredentialMutationFence(retained)).toBe(false); await create(new Scheduler(), async ({ fence }) => { retained = fence; expect(isCredentialMutationFence(fence)).toBe(true); return { status: "blocked" }; }).run(await f.authority()); expect(isCredentialMutationFence(retained)).toBe(false); });
  it("does not expose fence authority data and freezes its narrow surface", async () => { const f = new Fixture(); await create(new Scheduler(), async ({ fence }) => { expect(Object.isFrozen(fence)).toBe(true); expect(Reflect.ownKeys(fence)).toEqual(["beginCredentialInteraction", "renewBeforeCredentialMutation", "recordSubmitBarrier"]); expect(JSON.stringify(fence)).toBe("{}"); expect(JSON.stringify(fence)).not.toMatch(/owner|token|generation|repository|lease|secret/i); return { status: "blocked" }; }).run(await f.authority()); });
  it("blocks retained methods after execution settles without calling authority", async () => { const f = new Fixture(); let retained: { beginCredentialInteraction(): Promise<unknown>; renewBeforeCredentialMutation(): Promise<unknown>; recordSubmitBarrier(): Promise<unknown> } | undefined; await create(new Scheduler(), async ({ fence }) => { retained = fence; return { status: "blocked" }; }).run(await f.authority()); const calls = [...f.calls]; if (!retained) throw new Error("missing fence"); await expect(Promise.all([retained.beginCredentialInteraction(), retained.renewBeforeCredentialMutation(), retained.recordSubmitBarrier()])).resolves.toEqual([{ status: "blocked" }, { status: "blocked" }, { status: "blocked" }]); expect(f.calls).toEqual(calls); });
  it("unregisters an execution fence when execution throws", async () => { const f = new Fixture(); let retained: unknown; await create(new Scheduler(), async ({ fence }) => { retained = fence; throw new Error("execution"); }).run(await f.authority()); expect(isCredentialMutationFence(retained)).toBe(false); });
  it("keeps a prior run fence invalid during a subsequent execution", async () => { const first = new Fixture(); const second = new Fixture(); let prior: unknown; let executions = 0; const runner = create(new Scheduler(), async ({ fence }) => { executions++; if (executions === 1) { prior = fence; expect(isCredentialMutationFence(fence)).toBe(true); } else { expect([isCredentialMutationFence(prior), isCredentialMutationFence(fence)]).toEqual([false, true]); } return { status: "blocked" }; }); await runner.run(await first.authority()); await runner.run(await second.authority()); expect(isCredentialMutationFence(prior)).toBe(false); });
  it("fences authenticated completion when external cancellation arrives during deferred heartbeat stop", async () => { const f = new Fixture(); const s = new Scheduler(); s.holdStop = deferred<void>(); const controller = new AbortController(); const run = create(s, async ({ fence }) => { await phase(fence, "submit_barrier_recorded"); return { status: "succeeded" }; }, controller.signal).run(await f.authority()); await s.stopped.promise; controller.abort(); s.holdStop.resolve(); await expect(run).resolves.toEqual({ status: "unresolved" }); expect([terminal(f), s.stops]).toEqual([[], 1]); });
  it("does not execute or retain a listener for a pre-aborted external cancellation signal", async () => { const f = new Fixture(); const s = new Scheduler(); const controller = new AbortController(); controller.abort(); let executions = 0; await expect(create(s, async () => { executions++; return { status: "succeeded" }; }, controller.signal).run(await f.authority())).resolves.toEqual({ status: "unresolved" }); controller.abort(); expect([executions, s.starts, f.calls]).toEqual([0, 0, []]); });
  it("removes external cancellation listeners after success and heartbeat-start failure", async () => { for (const startError of [false, true]) { const f = new Fixture(); const s = new Scheduler(); s.startError = startError; const controller = new AbortController(); const outcome = await create(s, async ({ fence }) => { await phase(fence, "submit_barrier_recorded"); return { status: "succeeded" }; }, controller.signal).run(await f.authority()); const calls = [...f.calls]; controller.abort(); expect([outcome, f.calls]).toEqual([startError ? { status: "unresolved" } : { status: "authenticated" }, calls]); } });
  it("exports only the runner factory and fence predicate capability surface", () => { expect(Object.keys(subject).sort()).toEqual(["createAuthenticatedSessionMutationRunner", "isCredentialMutationFence"]); expect(Object.keys(subject).join(",")).not.toMatch(/create.*fence|register|unwrap/i); });
});
