import { describe, expect, it } from "vitest";
import { acquireAuthenticationMutationAuthority } from "../../modules/bank-sessions/authentication-mutation-authority";
import type { AuthenticationMutationAuthority } from "../../modules/bank-sessions/authentication-mutation-authority";
import type { SessionAuthenticationAttemptRepository, SessionAuthenticationAttemptRecord } from "../../modules/bank-sessions/session-authentication-attempt-repository";
import { createAuthenticatedSessionMutationRunner, type AuthenticationExecutionResult } from "./authenticated-session-mutation-runner";

const deferred = <T>() => { let resolve!: (value: T) => void; const promise = new Promise<T>((done) => { resolve = done; }); return { promise, resolve }; };
class Scheduler { callback?: () => Promise<void>; stopped = false; started = 0; stopError = false; async tick() { if (!this.stopped) await this.callback?.(); } start(callback: () => Promise<void>) { this.callback = callback; this.started++; return { stop: async () => { this.stopped = true; if (this.stopError) throw new Error("stop"); } }; } }
type Log = string[];
const authority = async (log: Log, options: { deny?: "begin" | "barrier"; renew?: "bad" | "throw"; terminal?: "bad" | "throw" } = {}): Promise<AuthenticationMutationAuthority> => {
  let phase = "no_credential_interaction"; const now = new Date(); const identity = { bankCode: "bank", runId: "run", attemptId: "attempt" }; const active = () => ({ identity, status: "active" as const, interactionPhase: phase as "no_credential_interaction" | "credentials_may_have_reached_portal" | "submit_may_have_been_dispatched", failureClass: null, operatorReason: null, retryCount: 0, ownerToken: "owner", generation: 0n, leaseExpiresAt: now, terminalAt: null, createdAt: now, updatedAt: now });
  const terminal = (status: "authenticated" | "failed", failure?: { failureClass: string; operatorReason: string }) => ({ ...active(), status, ownerToken: null, leaseExpiresAt: null, generation: 1n, terminalAt: now, failureClass: status === "failed" ? failure!.failureClass : null, operatorReason: status === "failed" ? failure!.operatorReason : null });
  const repository: SessionAuthenticationAttemptRepository = {
    findExact: async () => ({ status: "missing" }), getOrCreate: async () => ({ status: "created", record: { ...active(), ownerToken: null, leaseExpiresAt: null } }), acquireLease: async () => ({ status: "lease_acquired", owner: { identity, ownerToken: "owner", generation: 0n }, record: active() }), reconcileExpiredLease: async () => ({ status: "missing" }),
    renewLease: async () => { log.push(`renew:${phase}`); if (options.renew === "throw") throw new Error("renew"); return options.renew === "bad" ? { status: "not_applied" } : { status: "lease_renewed", record: active() }; },
    beginCredentialInteraction: async () => { log.push("begin"); if (options.deny === "begin") return { status: "not_applied" }; phase = "credentials_may_have_reached_portal"; return { status: "interaction_started", record: active() }; },
    recordSubmitBarrier: async () => { log.push("barrier"); if (options.deny === "barrier") return { status: "not_applied" }; phase = "submit_may_have_been_dispatched"; return { status: "recorded", record: active() }; },
    claimRetry: async () => { log.push("retry"); return { status: "retry_claimed", retryCount: 1, record: { ...active(), ownerToken: null, leaseExpiresAt: null, generation: 1n, retryCount: 1 } }; },
    completeAuthenticated: async () => { log.push("authenticated"); if (options.terminal === "throw") throw new Error("terminal"); return options.terminal === "bad" ? { status: "not_applied" } : { status: "authenticated", record: terminal("authenticated") as SessionAuthenticationAttemptRecord }; },
    completeFailed: async (failure) => { log.push(`failed:${failure.failureClass}`); if (options.terminal === "throw") throw new Error("terminal"); return options.terminal === "bad" ? { status: "not_applied" } : { status: "failed", record: terminal("failed", failure) as SessionAuthenticationAttemptRecord }; },
  };
  const minted = await acquireAuthenticationMutationAuthority({ identity, ownerToken: "owner", leaseDurationMs: 1, repository, probe: { observe: async () => ({ status: "unauthenticated" }) } });
  if (minted.status !== "authentication_required") throw new Error("mint"); return minted.authority;
};
const runner = (scheduler: Scheduler, execute: (input: { fence: { beginCredentialInteraction(): Promise<{ status: "authorized" | "blocked" }>; recordSubmitBarrier(): Promise<{ status: "authorized" | "blocked" }> }; signal: AbortSignal }) => Promise<AuthenticationExecutionResult>) => createAuthenticatedSessionMutationRunner({ execution: { execute }, heartbeat: scheduler });

describe("AuthenticatedSessionMutationRunner", () => {
  it("claims once; unavailable authority starts nothing", async () => { const s = new Scheduler(); const r = runner(s, async () => ({ status: "succeeded" })); const a = await authority([]); await expect(r.run(a)).resolves.toEqual({ status: "failed", reason: "authentication_attempt_requires_review" }); expect(s.started).toBe(1); await expect(r.run(a)).resolves.toEqual({ status: "unresolved" }); });
  it("starts heartbeat before execution, renews setup, and serializes all authority calls", async () => { const log: Log = []; const s = new Scheduler(); const setup = deferred<AuthenticationExecutionResult>(); const r = runner(s, async ({ fence }) => { log.push("execute"); await s.tick(); expect(await fence.beginCredentialInteraction()).toEqual({ status: "authorized" }); await s.tick(); expect(await fence.recordSubmitBarrier()).toEqual({ status: "authorized" }); return setup.promise; }); const run = r.run(await authority(log)); await new Promise((done) => setTimeout(done, 0)); setup.resolve({ status: "succeeded" }); await expect(run).resolves.toEqual({ status: "authenticated" }); expect(log).toEqual(["execute", "renew:no_credential_interaction", "begin", "renew:credentials_may_have_reached_portal", "barrier", "authenticated"]); });
  it("queues a tick behind a fence operation and drains stop before terminalization", async () => { const log: Log = []; const s = new Scheduler(); const gate = deferred<{ status: "authorized" | "blocked" }>(); const r = runner(s, async ({ fence }) => { const begin = fence.beginCredentialInteraction(); const tick = s.tick(); gate.resolve(await begin); await tick; return { status: "transient_unavailable" }; }); await expect(r.run(await authority(log))).resolves.toEqual({ status: "failed", reason: "authentication_attempt_requires_review" }); expect(log).toEqual(["begin", "renew:credentials_may_have_reached_portal", "failed:interaction_outcome_uncertain"]); await s.tick(); expect(log).toHaveLength(3); });
  it("makes heartbeat and fence failures sticky, aborts execution, and never terminalizes", async () => { for (const options of [{ renew: "bad" as const }, { renew: "throw" as const }, { deny: "begin" as const }, { deny: "barrier" as const }]) { const log: Log = []; const s = new Scheduler(); const r = runner(s, async ({ fence, signal }) => { if (options.deny !== "barrier") await s.tick(); await fence.beginCredentialInteraction(); if (options.deny === "barrier") { await fence.recordSubmitBarrier(); } expect(signal.aborted).toBe(true); return { status: "succeeded" }; }); await expect(r.run(await authority(log, options))).resolves.toEqual({ status: "unresolved" }); expect(log.some((entry) => entry.startsWith("failed") || entry === "authenticated" || entry === "retry")).toBe(false); } });
  it("fails closed when scheduler stop fails", async () => { const s = new Scheduler(); s.stopError = true; const log: Log = []; await expect(runner(s, async () => ({ status: "succeeded" })).run(await authority(log))).resolves.toEqual({ status: "unresolved" }); expect(log).toEqual([]); });
  it("maps every execution result and never retries after interaction", async () => { const cases: Array<[AuthenticationExecutionResult | unknown, "leased" | "started" | "submitted", unknown]> = [[{ status: "transient_unavailable" }, "leased", { status: "retry_claimed" }], [{ status: "cancelled" }, "leased", { status: "retry_claimed" }], [{ status: "succeeded" }, "leased", { status: "failed", reason: "authentication_attempt_requires_review" }], [{ status: "succeeded" }, "started", { status: "failed", reason: "authentication_attempt_requires_review" }], [{ status: "succeeded" }, "submitted", { status: "authenticated" }], [{ status: "transient_unavailable" }, "started", { status: "failed", reason: "authentication_attempt_requires_review" }], [{ status: "cancelled" }, "submitted", { status: "failed", reason: "authentication_attempt_requires_review" }], [{ status: "rejected", cause: "protected_or_mfa" }, "leased", { status: "failed", reason: "protected_authentication_step_detected" }], [{ status: "rejected", cause: "incompatible_flow" }, "leased", { status: "failed", reason: "bank_login_configuration_requires_review" }], [{ status: "rejected", cause: "structural_configuration" }, "leased", { status: "failed", reason: "bank_login_configuration_requires_review" }], [{ status: "rejected", cause: "unknown" }, "started", { status: "failed", reason: "authentication_attempt_requires_review" }], [{ status: "blocked" }, "submitted", { status: "failed", reason: "authentication_attempt_requires_review" }]]; for (const [result, phase, expected] of cases) { const log: Log = []; const s = new Scheduler(); const r = runner(s, async ({ fence }) => { if (phase !== "leased") await fence.beginCredentialInteraction(); if (phase === "submitted") await fence.recordSubmitBarrier(); return result as AuthenticationExecutionResult; }); await expect(r.run(await authority(log))).resolves.toEqual(expected); expect(phase === "leased" ? log.includes("retry") || log.some((x) => x.startsWith("failed")) : !log.includes("retry")).toBe(true); } });
  it("does not replay terminal calls and rejects malformed or sensitive execution output without leaks", async () => { for (const result of [null, 1, { status: "succeeded", password: "secret" }, { status: "rejected", cause: "unknown", token: "secret" }]) { const log: Log = []; const outcome = await runner(new Scheduler(), async () => result as AuthenticationExecutionResult).run(await authority(log, { terminal: "bad" })); expect(outcome).toEqual({ status: "unresolved" }); expect(JSON.stringify(outcome)).not.toContain("secret"); expect(log.filter((x) => x.startsWith("failed") || x === "authenticated")).toHaveLength(1); } });
  it("handles execution throw and exposes no authority capability through its result", async () => { const log: Log = []; const outcome = await runner(new Scheduler(), async () => { throw new Error("secret"); }).run(await authority(log)); expect(outcome).toEqual({ status: "failed", reason: "authentication_attempt_requires_review" }); expect(JSON.stringify(outcome)).not.toMatch(/owner|token|error|secret/); });
});
